site_name: GoDesk Docs
site_url: http://godesk.uk/document/
site_dir: site

theme:
    name: 'material'
    icon:
        repo: fontawesome/brands/github

plugins:
  - search

  - i18n:
      docs_structure: folder   # 改成 folder，按文件夹区分语言
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          name: English
          build: true
          default: true

        - locale: zh
          name: 简体中文
          build: true

          nav_translations: # 导航栏翻译，不可以有缩进
            HOME: 首页
            Manager Server Config: 管理服务端配置

nav:
  - HOME: index.md
  - Manager Server Config: manager-env.md

extra:
  generator: false
  social:
    - icon: fontawesome/solid/globe
      link: http://godesk.uk
      name: Offical Website
    - icon: fontawesome/brands/github
      link: https://github.com/rgaa-software/gammaray
      name: Github